name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0

      - name: Checkout
        uses: actions/checkout@master

      - name: Install && Build
        run: |
          npm install
          npm run build

      - name: Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          # CLEAN_EXCLUDE: '["css", "js"]'

      - name: OSS
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{secrets.AccessKey_ID}}
          access-key-secret: ${{secrets.Access_Key_Secret}}
      - run: ossutil cp -rf dist oss://jx3box/static/bbs
      - run: ossutil cp -rf dist oss://jx3box-www/bbs
